# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from account_manager.models.base_model_ import Model
from account_manager import util


class AccountRecoveryRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, email=None):  # noqa: E501
        """AccountRecoveryRequest - a model defined in OpenAPI

        :param email: The email of this AccountRecoveryRequest.  # noqa: E501
        :type email: str
        """
        self.openapi_types = {
            'email': str
        }

        self.attribute_map = {
            'email': 'email'
        }

        self._email = email

    @classmethod
    def from_dict(cls, dikt) -> 'AccountRecoveryRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AccountRecoveryRequest of this AccountRecoveryRequest.  # noqa: E501
        :rtype: AccountRecoveryRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def email(self):
        """Gets the email of this AccountRecoveryRequest.


        :return: The email of this AccountRecoveryRequest.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this AccountRecoveryRequest.


        :param email: The email of this AccountRecoveryRequest.
        :type email: str
        """
        if email is None:
            raise ValueError("Invalid value for `email`, must not be `None`")  # noqa: E501
        if email is not None and len(email) > 50:
            raise ValueError("Invalid value for `email`, length must be less than or equal to `50`")  # noqa: E501

        self._email = email
