# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from account_manager.models.base_model_ import Model
from account_manager import util


class ContractedPower(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    _1_15_KVA = "1.15 kVA"
    _2_3_KVA = "2.3 kVA"
    _3_45_KVA = "3.45 kVA"
    _4_6_KVA = "4.6 kVA"
    _5_75_KVA = "5.75 kVA"
    _6_9_KVA = "6.9 kVA"
    _10_35_KVA = "10.35 kVA"
    _13_8_KVA = "13.8 kVA"
    _17_25_KVA = "17.25 kVA"
    _20_7_KVA = "20.7 kVA"
    _27_6_KVA = "27.6 kVA"
    _34_5_KVA = "34.5 kVA"
    _41_4_KVA = "41.4 kVA"
    _27_6_KVA = "27.6 kVA"
    _34_5_KVA = "34.5 kVA"
    _41_4_KVA = "41.4 kVA"
    def __init__(self):  # noqa: E501
        """ContractedPower - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'ContractedPower':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ContractedPower of this ContractedPower.  # noqa: E501
        :rtype: ContractedPower
        """
        return util.deserialize_model(dikt, cls)
