# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from account_manager.models.base_model_ import Model
from account_manager import util


class CurrentAppVersion(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, build_version=None):  # noqa: E501
        """CurrentAppVersion - a model defined in OpenAPI

        :param build_version: The build_version of this CurrentAppVersion.  # noqa: E501
        :type build_version: str
        """
        self.openapi_types = {
            'build_version': str
        }

        self.attribute_map = {
            'build_version': 'build_version'
        }

        self._build_version = build_version

    @classmethod
    def from_dict(cls, dikt) -> 'CurrentAppVersion':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CurrentAppVersion of this CurrentAppVersion.  # noqa: E501
        :rtype: CurrentAppVersion
        """
        return util.deserialize_model(dikt, cls)

    @property
    def build_version(self):
        """Gets the build_version of this CurrentAppVersion.


        :return: The build_version of this CurrentAppVersion.
        :rtype: str
        """
        return self._build_version

    @build_version.setter
    def build_version(self, build_version):
        """Sets the build_version of this CurrentAppVersion.


        :param build_version: The build_version of this CurrentAppVersion.
        :type build_version: str
        """

        self._build_version = build_version
