# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from account_manager.models.base_model_ import Model
from account_manager import util


class Dongles(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, user_id=None, api_key=None):  # noqa: E501
        """Dongles - a model defined in OpenAPI

        :param user_id: The user_id of this Dongles.  # noqa: E501
        :type user_id: str
        :param api_key: The api_key of this Dongles.  # noqa: E501
        :type api_key: str
        """
        self.openapi_types = {
            'user_id': str,
            'api_key': str
        }

        self.attribute_map = {
            'user_id': 'user_id',
            'api_key': 'api_key'
        }

        self._user_id = user_id
        self._api_key = api_key

    @classmethod
    def from_dict(cls, dikt) -> 'Dongles':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Dongles of this Dongles.  # noqa: E501
        :rtype: Dongles
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user_id(self):
        """Gets the user_id of this Dongles.


        :return: The user_id of this Dongles.
        :rtype: str
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id):
        """Sets the user_id of this Dongles.


        :param user_id: The user_id of this Dongles.
        :type user_id: str
        """
        if user_id is not None and len(user_id) > 10:
            raise ValueError("Invalid value for `user_id`, length must be less than or equal to `10`")  # noqa: E501
        if user_id is not None and len(user_id) < 10:
            raise ValueError("Invalid value for `user_id`, length must be greater than or equal to `10`")  # noqa: E501

        self._user_id = user_id

    @property
    def api_key(self):
        """Gets the api_key of this Dongles.


        :return: The api_key of this Dongles.
        :rtype: str
        """
        return self._api_key

    @api_key.setter
    def api_key(self, api_key):
        """Sets the api_key of this Dongles.


        :param api_key: The api_key of this Dongles.
        :type api_key: str
        """

        self._api_key = api_key
