# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from account_manager.models.base_model_ import Model
from account_manager import util


class GoogleUserRegisterRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, first_name=None, last_name=None, email=None):  # noqa: E501
        """GoogleUserRegisterRequest - a model defined in OpenAPI

        :param first_name: The first_name of this GoogleUserRegisterRequest.  # noqa: E501
        :type first_name: str
        :param last_name: The last_name of this GoogleUserRegisterRequest.  # noqa: E501
        :type last_name: str
        :param email: The email of this GoogleUserRegisterRequest.  # noqa: E501
        :type email: str
        """
        self.openapi_types = {
            'first_name': str,
            'last_name': str,
            'email': str
        }

        self.attribute_map = {
            'first_name': 'first_name',
            'last_name': 'last_name',
            'email': 'email'
        }

        self._first_name = first_name
        self._last_name = last_name
        self._email = email

    @classmethod
    def from_dict(cls, dikt) -> 'GoogleUserRegisterRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GoogleUserRegisterRequest of this GoogleUserRegisterRequest.  # noqa: E501
        :rtype: GoogleUserRegisterRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def first_name(self):
        """Gets the first_name of this GoogleUserRegisterRequest.


        :return: The first_name of this GoogleUserRegisterRequest.
        :rtype: str
        """
        return self._first_name

    @first_name.setter
    def first_name(self, first_name):
        """Sets the first_name of this GoogleUserRegisterRequest.


        :param first_name: The first_name of this GoogleUserRegisterRequest.
        :type first_name: str
        """
        if first_name is None:
            raise ValueError("Invalid value for `first_name`, must not be `None`")  # noqa: E501
        if first_name is not None and len(first_name) > 15:
            raise ValueError("Invalid value for `first_name`, length must be less than or equal to `15`")  # noqa: E501
        if first_name is not None and len(first_name) < 1:
            raise ValueError("Invalid value for `first_name`, length must be greater than or equal to `1`")  # noqa: E501

        self._first_name = first_name

    @property
    def last_name(self):
        """Gets the last_name of this GoogleUserRegisterRequest.


        :return: The last_name of this GoogleUserRegisterRequest.
        :rtype: str
        """
        return self._last_name

    @last_name.setter
    def last_name(self, last_name):
        """Sets the last_name of this GoogleUserRegisterRequest.


        :param last_name: The last_name of this GoogleUserRegisterRequest.
        :type last_name: str
        """
        if last_name is not None and len(last_name) > 15:
            raise ValueError("Invalid value for `last_name`, length must be less than or equal to `15`")  # noqa: E501
        if last_name is not None and len(last_name) < 1:
            raise ValueError("Invalid value for `last_name`, length must be greater than or equal to `1`")  # noqa: E501

        self._last_name = last_name

    @property
    def email(self):
        """Gets the email of this GoogleUserRegisterRequest.


        :return: The email of this GoogleUserRegisterRequest.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this GoogleUserRegisterRequest.


        :param email: The email of this GoogleUserRegisterRequest.
        :type email: str
        """
        if email is None:
            raise ValueError("Invalid value for `email`, must not be `None`")  # noqa: E501
        if email is not None and len(email) > 50:
            raise ValueError("Invalid value for `email`, length must be less than or equal to `50`")  # noqa: E501

        self._email = email
