# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from account_manager.models.base_model_ import Model
from account_manager import util


class InfoMessages(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, title=None, description=None, icon=None):  # noqa: E501
        """InfoMessages - a model defined in OpenAPI

        :param title: The title of this InfoMessages.  # noqa: E501
        :type title: str
        :param description: The description of this InfoMessages.  # noqa: E501
        :type description: str
        :param icon: The icon of this InfoMessages.  # noqa: E501
        :type icon: str
        """
        self.openapi_types = {
            'title': str,
            'description': str,
            'icon': str
        }

        self.attribute_map = {
            'title': 'title',
            'description': 'description',
            'icon': 'icon'
        }

        self._title = title
        self._description = description
        self._icon = icon

    @classmethod
    def from_dict(cls, dikt) -> 'InfoMessages':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The InfoMessages of this InfoMessages.  # noqa: E501
        :rtype: InfoMessages
        """
        return util.deserialize_model(dikt, cls)

    @property
    def title(self):
        """Gets the title of this InfoMessages.


        :return: The title of this InfoMessages.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this InfoMessages.


        :param title: The title of this InfoMessages.
        :type title: str
        """

        self._title = title

    @property
    def description(self):
        """Gets the description of this InfoMessages.


        :return: The description of this InfoMessages.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this InfoMessages.


        :param description: The description of this InfoMessages.
        :type description: str
        """

        self._description = description

    @property
    def icon(self):
        """Gets the icon of this InfoMessages.


        :return: The icon of this InfoMessages.
        :rtype: str
        """
        return self._icon

    @icon.setter
    def icon(self, icon):
        """Sets the icon of this InfoMessages.


        :param icon: The icon of this InfoMessages.
        :type icon: str
        """

        self._icon = icon
