# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from account_manager.models.base_model_ import Model
from account_manager import util


class MeterIdToUserId(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, meter_id=None, user_id=None):  # noqa: E501
        """MeterIdToUserId - a model defined in OpenAPI

        :param meter_id: The meter_id of this MeterIdToUserId.  # noqa: E501
        :type meter_id: str
        :param user_id: The user_id of this MeterIdToUserId.  # noqa: E501
        :type user_id: str
        """
        self.openapi_types = {
            'meter_id': str,
            'user_id': str
        }

        self.attribute_map = {
            'meter_id': 'meter_id',
            'user_id': 'user_id'
        }

        self._meter_id = meter_id
        self._user_id = user_id

    @classmethod
    def from_dict(cls, dikt) -> 'MeterIdToUserId':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The MeterIdToUserId of this MeterIdToUserId.  # noqa: E501
        :rtype: MeterIdToUserId
        """
        return util.deserialize_model(dikt, cls)

    @property
    def meter_id(self):
        """Gets the meter_id of this MeterIdToUserId.


        :return: The meter_id of this MeterIdToUserId.
        :rtype: str
        """
        return self._meter_id

    @meter_id.setter
    def meter_id(self, meter_id):
        """Sets the meter_id of this MeterIdToUserId.


        :param meter_id: The meter_id of this MeterIdToUserId.
        :type meter_id: str
        """
        if meter_id is None:
            raise ValueError("Invalid value for `meter_id`, must not be `None`")  # noqa: E501

        self._meter_id = meter_id

    @property
    def user_id(self):
        """Gets the user_id of this MeterIdToUserId.


        :return: The user_id of this MeterIdToUserId.
        :rtype: str
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id):
        """Sets the user_id of this MeterIdToUserId.


        :param user_id: The user_id of this MeterIdToUserId.
        :type user_id: str
        """
        if user_id is None:
            raise ValueError("Invalid value for `user_id`, must not be `None`")  # noqa: E501
        if user_id is not None and len(user_id) > 10:
            raise ValueError("Invalid value for `user_id`, length must be less than or equal to `10`")  # noqa: E501
        if user_id is not None and len(user_id) < 10:
            raise ValueError("Invalid value for `user_id`, length must be greater than or equal to `10`")  # noqa: E501

        self._user_id = user_id
