# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from account_manager.models.base_model_ import Model
from account_manager.models.contracted_power import ContractedPower
from account_manager.models.country import Country
from account_manager.models.not_disturb import NotDisturb
from account_manager.models.schedule_type import ScheduleType
from account_manager.models.tarif_type import TarifType
import re
from account_manager import util

from account_manager.models.contracted_power import ContractedPower  # noqa: E501
from account_manager.models.country import Country  # noqa: E501
from account_manager.models.not_disturb import NotDisturb  # noqa: E501
from account_manager.models.schedule_type import ScheduleType  # noqa: E501
from account_manager.models.tarif_type import TarifType  # noqa: E501
import re  # noqa: E501

class NewSettingsRequestBody(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, user_id=None, first_name=None, last_name=None, email=None, schedule_type=None, meter_id=None, wp_token=None, country=None, postal_code=None, tarif_type=None, contracted_power=None, not_disturb=None, global_optimizer=None):  # noqa: E501
        """NewSettingsRequestBody - a model defined in OpenAPI

        :param user_id: The user_id of this NewSettingsRequestBody.  # noqa: E501
        :type user_id: str
        :param first_name: The first_name of this NewSettingsRequestBody.  # noqa: E501
        :type first_name: str
        :param last_name: The last_name of this NewSettingsRequestBody.  # noqa: E501
        :type last_name: str
        :param email: The email of this NewSettingsRequestBody.  # noqa: E501
        :type email: str
        :param schedule_type: The schedule_type of this NewSettingsRequestBody.  # noqa: E501
        :type schedule_type: ScheduleType
        :param meter_id: The meter_id of this NewSettingsRequestBody.  # noqa: E501
        :type meter_id: str
        :param wp_token: The wp_token of this NewSettingsRequestBody.  # noqa: E501
        :type wp_token: str
        :param country: The country of this NewSettingsRequestBody.  # noqa: E501
        :type country: Country
        :param postal_code: The postal_code of this NewSettingsRequestBody.  # noqa: E501
        :type postal_code: str
        :param tarif_type: The tarif_type of this NewSettingsRequestBody.  # noqa: E501
        :type tarif_type: TarifType
        :param contracted_power: The contracted_power of this NewSettingsRequestBody.  # noqa: E501
        :type contracted_power: ContractedPower
        :param not_disturb: The not_disturb of this NewSettingsRequestBody.  # noqa: E501
        :type not_disturb: NotDisturb
        :param global_optimizer: The global_optimizer of this NewSettingsRequestBody.  # noqa: E501
        :type global_optimizer: bool
        """
        self.openapi_types = {
            'user_id': str,
            'first_name': str,
            'last_name': str,
            'email': str,
            'schedule_type': ScheduleType,
            'meter_id': str,
            'wp_token': str,
            'country': Country,
            'postal_code': str,
            'tarif_type': TarifType,
            'contracted_power': ContractedPower,
            'not_disturb': NotDisturb,
            'global_optimizer': bool
        }

        self.attribute_map = {
            'user_id': 'user_id',
            'first_name': 'first_name',
            'last_name': 'last_name',
            'email': 'email',
            'schedule_type': 'schedule_type',
            'meter_id': 'meter_id',
            'wp_token': 'wp_token',
            'country': 'country',
            'postal_code': 'postal_code',
            'tarif_type': 'tarif_type',
            'contracted_power': 'contracted_power',
            'not_disturb': 'not_disturb',
            'global_optimizer': 'global_optimizer'
        }

        self._user_id = user_id
        self._first_name = first_name
        self._last_name = last_name
        self._email = email
        self._schedule_type = schedule_type
        self._meter_id = meter_id
        self._wp_token = wp_token
        self._country = country
        self._postal_code = postal_code
        self._tarif_type = tarif_type
        self._contracted_power = contracted_power
        self._not_disturb = not_disturb
        self._global_optimizer = global_optimizer

    @classmethod
    def from_dict(cls, dikt) -> 'NewSettingsRequestBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The NewSettingsRequestBody of this NewSettingsRequestBody.  # noqa: E501
        :rtype: NewSettingsRequestBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user_id(self):
        """Gets the user_id of this NewSettingsRequestBody.


        :return: The user_id of this NewSettingsRequestBody.
        :rtype: str
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id):
        """Sets the user_id of this NewSettingsRequestBody.


        :param user_id: The user_id of this NewSettingsRequestBody.
        :type user_id: str
        """
        if user_id is None:
            raise ValueError("Invalid value for `user_id`, must not be `None`")  # noqa: E501
        if user_id is not None and len(user_id) > 10:
            raise ValueError("Invalid value for `user_id`, length must be less than or equal to `10`")  # noqa: E501
        if user_id is not None and len(user_id) < 10:
            raise ValueError("Invalid value for `user_id`, length must be greater than or equal to `10`")  # noqa: E501

        self._user_id = user_id

    @property
    def first_name(self):
        """Gets the first_name of this NewSettingsRequestBody.


        :return: The first_name of this NewSettingsRequestBody.
        :rtype: str
        """
        return self._first_name

    @first_name.setter
    def first_name(self, first_name):
        """Sets the first_name of this NewSettingsRequestBody.


        :param first_name: The first_name of this NewSettingsRequestBody.
        :type first_name: str
        """
        if first_name is None:
            raise ValueError("Invalid value for `first_name`, must not be `None`")  # noqa: E501
        if first_name is not None and len(first_name) > 15:
            raise ValueError("Invalid value for `first_name`, length must be less than or equal to `15`")  # noqa: E501
        if first_name is not None and len(first_name) < 1:
            raise ValueError("Invalid value for `first_name`, length must be greater than or equal to `1`")  # noqa: E501

        self._first_name = first_name

    @property
    def last_name(self):
        """Gets the last_name of this NewSettingsRequestBody.


        :return: The last_name of this NewSettingsRequestBody.
        :rtype: str
        """
        return self._last_name

    @last_name.setter
    def last_name(self, last_name):
        """Sets the last_name of this NewSettingsRequestBody.


        :param last_name: The last_name of this NewSettingsRequestBody.
        :type last_name: str
        """
        if last_name is not None and len(last_name) > 15:
            raise ValueError("Invalid value for `last_name`, length must be less than or equal to `15`")  # noqa: E501
        if last_name is not None and len(last_name) < 1:
            raise ValueError("Invalid value for `last_name`, length must be greater than or equal to `1`")  # noqa: E501

        self._last_name = last_name

    @property
    def email(self):
        """Gets the email of this NewSettingsRequestBody.


        :return: The email of this NewSettingsRequestBody.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this NewSettingsRequestBody.


        :param email: The email of this NewSettingsRequestBody.
        :type email: str
        """
        if email is None:
            raise ValueError("Invalid value for `email`, must not be `None`")  # noqa: E501
        if email is not None and len(email) > 50:
            raise ValueError("Invalid value for `email`, length must be less than or equal to `50`")  # noqa: E501

        self._email = email

    @property
    def schedule_type(self):
        """Gets the schedule_type of this NewSettingsRequestBody.


        :return: The schedule_type of this NewSettingsRequestBody.
        :rtype: ScheduleType
        """
        return self._schedule_type

    @schedule_type.setter
    def schedule_type(self, schedule_type):
        """Sets the schedule_type of this NewSettingsRequestBody.


        :param schedule_type: The schedule_type of this NewSettingsRequestBody.
        :type schedule_type: ScheduleType
        """

        self._schedule_type = schedule_type

    @property
    def meter_id(self):
        """Gets the meter_id of this NewSettingsRequestBody.


        :return: The meter_id of this NewSettingsRequestBody.
        :rtype: str
        """
        return self._meter_id

    @meter_id.setter
    def meter_id(self, meter_id):
        """Sets the meter_id of this NewSettingsRequestBody.


        :param meter_id: The meter_id of this NewSettingsRequestBody.
        :type meter_id: str
        """

        self._meter_id = meter_id

    @property
    def wp_token(self):
        """Gets the wp_token of this NewSettingsRequestBody.


        :return: The wp_token of this NewSettingsRequestBody.
        :rtype: str
        """
        return self._wp_token

    @wp_token.setter
    def wp_token(self, wp_token):
        """Sets the wp_token of this NewSettingsRequestBody.


        :param wp_token: The wp_token of this NewSettingsRequestBody.
        :type wp_token: str
        """

        self._wp_token = wp_token

    @property
    def country(self):
        """Gets the country of this NewSettingsRequestBody.


        :return: The country of this NewSettingsRequestBody.
        :rtype: Country
        """
        return self._country

    @country.setter
    def country(self, country):
        """Sets the country of this NewSettingsRequestBody.


        :param country: The country of this NewSettingsRequestBody.
        :type country: Country
        """

        self._country = country

    @property
    def postal_code(self):
        """Gets the postal_code of this NewSettingsRequestBody.


        :return: The postal_code of this NewSettingsRequestBody.
        :rtype: str
        """
        return self._postal_code

    @postal_code.setter
    def postal_code(self, postal_code):
        """Sets the postal_code of this NewSettingsRequestBody.


        :param postal_code: The postal_code of this NewSettingsRequestBody.
        :type postal_code: str
        """
        if postal_code is not None and not re.search(r'^[0-9]{4}-[0-9]{3}$', postal_code):  # noqa: E501
            raise ValueError("Invalid value for `postal_code`, must be a follow pattern or equal to `/^[0-9]{4}-[0-9]{3}$/`")  # noqa: E501

        self._postal_code = postal_code

    @property
    def tarif_type(self):
        """Gets the tarif_type of this NewSettingsRequestBody.


        :return: The tarif_type of this NewSettingsRequestBody.
        :rtype: TarifType
        """
        return self._tarif_type

    @tarif_type.setter
    def tarif_type(self, tarif_type):
        """Sets the tarif_type of this NewSettingsRequestBody.


        :param tarif_type: The tarif_type of this NewSettingsRequestBody.
        :type tarif_type: TarifType
        """

        self._tarif_type = tarif_type

    @property
    def contracted_power(self):
        """Gets the contracted_power of this NewSettingsRequestBody.


        :return: The contracted_power of this NewSettingsRequestBody.
        :rtype: ContractedPower
        """
        return self._contracted_power

    @contracted_power.setter
    def contracted_power(self, contracted_power):
        """Sets the contracted_power of this NewSettingsRequestBody.


        :param contracted_power: The contracted_power of this NewSettingsRequestBody.
        :type contracted_power: ContractedPower
        """

        self._contracted_power = contracted_power

    @property
    def not_disturb(self):
        """Gets the not_disturb of this NewSettingsRequestBody.


        :return: The not_disturb of this NewSettingsRequestBody.
        :rtype: NotDisturb
        """
        return self._not_disturb

    @not_disturb.setter
    def not_disturb(self, not_disturb):
        """Sets the not_disturb of this NewSettingsRequestBody.


        :param not_disturb: The not_disturb of this NewSettingsRequestBody.
        :type not_disturb: NotDisturb
        """

        self._not_disturb = not_disturb

    @property
    def global_optimizer(self):
        """Gets the global_optimizer of this NewSettingsRequestBody.


        :return: The global_optimizer of this NewSettingsRequestBody.
        :rtype: bool
        """
        return self._global_optimizer

    @global_optimizer.setter
    def global_optimizer(self, global_optimizer):
        """Sets the global_optimizer of this NewSettingsRequestBody.


        :param global_optimizer: The global_optimizer of this NewSettingsRequestBody.
        :type global_optimizer: bool
        """

        self._global_optimizer = global_optimizer
