# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from account_manager.models.base_model_ import Model
from account_manager.models.contracted_power import ContractedPower
from account_manager.models.country import Country
from account_manager.models.schedule_type import ScheduleType
from account_manager.models.tarif_type import TarifType
import re
from account_manager import util

from account_manager.models.contracted_power import ContractedPower  # noqa: E501
from account_manager.models.country import Country  # noqa: E501
from account_manager.models.schedule_type import ScheduleType  # noqa: E501
from account_manager.models.tarif_type import TarifType  # noqa: E501
import re  # noqa: E501

class RegisterRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, first_name=None, last_name=None, email=None, password=None, password_repeat=None, meter_id=None, country=None, postal_code=None, tarif_type=None, contracted_power=None, schedule_type=None):  # noqa: E501
        """RegisterRequest - a model defined in OpenAPI

        :param first_name: The first_name of this RegisterRequest.  # noqa: E501
        :type first_name: str
        :param last_name: The last_name of this RegisterRequest.  # noqa: E501
        :type last_name: str
        :param email: The email of this RegisterRequest.  # noqa: E501
        :type email: str
        :param password: The password of this RegisterRequest.  # noqa: E501
        :type password: str
        :param password_repeat: The password_repeat of this RegisterRequest.  # noqa: E501
        :type password_repeat: str
        :param meter_id: The meter_id of this RegisterRequest.  # noqa: E501
        :type meter_id: str
        :param country: The country of this RegisterRequest.  # noqa: E501
        :type country: Country
        :param postal_code: The postal_code of this RegisterRequest.  # noqa: E501
        :type postal_code: str
        :param tarif_type: The tarif_type of this RegisterRequest.  # noqa: E501
        :type tarif_type: TarifType
        :param contracted_power: The contracted_power of this RegisterRequest.  # noqa: E501
        :type contracted_power: ContractedPower
        :param schedule_type: The schedule_type of this RegisterRequest.  # noqa: E501
        :type schedule_type: ScheduleType
        """
        self.openapi_types = {
            'first_name': str,
            'last_name': str,
            'email': str,
            'password': str,
            'password_repeat': str,
            'meter_id': str,
            'country': Country,
            'postal_code': str,
            'tarif_type': TarifType,
            'contracted_power': ContractedPower,
            'schedule_type': ScheduleType
        }

        self.attribute_map = {
            'first_name': 'first_name',
            'last_name': 'last_name',
            'email': 'email',
            'password': 'password',
            'password_repeat': 'password_repeat',
            'meter_id': 'meter_id',
            'country': 'country',
            'postal_code': 'postal_code',
            'tarif_type': 'tarif_type',
            'contracted_power': 'contracted_power',
            'schedule_type': 'schedule_type'
        }

        self._first_name = first_name
        self._last_name = last_name
        self._email = email
        self._password = password
        self._password_repeat = password_repeat
        self._meter_id = meter_id
        self._country = country
        self._postal_code = postal_code
        self._tarif_type = tarif_type
        self._contracted_power = contracted_power
        self._schedule_type = schedule_type

    @classmethod
    def from_dict(cls, dikt) -> 'RegisterRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RegisterRequest of this RegisterRequest.  # noqa: E501
        :rtype: RegisterRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def first_name(self):
        """Gets the first_name of this RegisterRequest.


        :return: The first_name of this RegisterRequest.
        :rtype: str
        """
        return self._first_name

    @first_name.setter
    def first_name(self, first_name):
        """Sets the first_name of this RegisterRequest.


        :param first_name: The first_name of this RegisterRequest.
        :type first_name: str
        """
        if first_name is None:
            raise ValueError("Invalid value for `first_name`, must not be `None`")  # noqa: E501
        if first_name is not None and len(first_name) > 15:
            raise ValueError("Invalid value for `first_name`, length must be less than or equal to `15`")  # noqa: E501
        if first_name is not None and len(first_name) < 1:
            raise ValueError("Invalid value for `first_name`, length must be greater than or equal to `1`")  # noqa: E501

        self._first_name = first_name

    @property
    def last_name(self):
        """Gets the last_name of this RegisterRequest.


        :return: The last_name of this RegisterRequest.
        :rtype: str
        """
        return self._last_name

    @last_name.setter
    def last_name(self, last_name):
        """Sets the last_name of this RegisterRequest.


        :param last_name: The last_name of this RegisterRequest.
        :type last_name: str
        """
        if last_name is not None and len(last_name) > 15:
            raise ValueError("Invalid value for `last_name`, length must be less than or equal to `15`")  # noqa: E501
        if last_name is not None and len(last_name) < 1:
            raise ValueError("Invalid value for `last_name`, length must be greater than or equal to `1`")  # noqa: E501

        self._last_name = last_name

    @property
    def email(self):
        """Gets the email of this RegisterRequest.


        :return: The email of this RegisterRequest.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this RegisterRequest.


        :param email: The email of this RegisterRequest.
        :type email: str
        """
        if email is None:
            raise ValueError("Invalid value for `email`, must not be `None`")  # noqa: E501
        if email is not None and len(email) > 50:
            raise ValueError("Invalid value for `email`, length must be less than or equal to `50`")  # noqa: E501

        self._email = email

    @property
    def password(self):
        """Gets the password of this RegisterRequest.


        :return: The password of this RegisterRequest.
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password):
        """Sets the password of this RegisterRequest.


        :param password: The password of this RegisterRequest.
        :type password: str
        """
        if password is None:
            raise ValueError("Invalid value for `password`, must not be `None`")  # noqa: E501
        if password is not None and len(password) > 30:
            raise ValueError("Invalid value for `password`, length must be less than or equal to `30`")  # noqa: E501
        if password is not None and len(password) < 6:
            raise ValueError("Invalid value for `password`, length must be greater than or equal to `6`")  # noqa: E501

        self._password = password

    @property
    def password_repeat(self):
        """Gets the password_repeat of this RegisterRequest.


        :return: The password_repeat of this RegisterRequest.
        :rtype: str
        """
        return self._password_repeat

    @password_repeat.setter
    def password_repeat(self, password_repeat):
        """Sets the password_repeat of this RegisterRequest.


        :param password_repeat: The password_repeat of this RegisterRequest.
        :type password_repeat: str
        """
        if password_repeat is None:
            raise ValueError("Invalid value for `password_repeat`, must not be `None`")  # noqa: E501
        if password_repeat is not None and len(password_repeat) > 30:
            raise ValueError("Invalid value for `password_repeat`, length must be less than or equal to `30`")  # noqa: E501
        if password_repeat is not None and len(password_repeat) < 6:
            raise ValueError("Invalid value for `password_repeat`, length must be greater than or equal to `6`")  # noqa: E501

        self._password_repeat = password_repeat

    @property
    def meter_id(self):
        """Gets the meter_id of this RegisterRequest.


        :return: The meter_id of this RegisterRequest.
        :rtype: str
        """
        return self._meter_id

    @meter_id.setter
    def meter_id(self, meter_id):
        """Sets the meter_id of this RegisterRequest.


        :param meter_id: The meter_id of this RegisterRequest.
        :type meter_id: str
        """
        if meter_id is None:
            raise ValueError("Invalid value for `meter_id`, must not be `None`")  # noqa: E501

        self._meter_id = meter_id

    @property
    def country(self):
        """Gets the country of this RegisterRequest.


        :return: The country of this RegisterRequest.
        :rtype: Country
        """
        return self._country

    @country.setter
    def country(self, country):
        """Sets the country of this RegisterRequest.


        :param country: The country of this RegisterRequest.
        :type country: Country
        """

        self._country = country

    @property
    def postal_code(self):
        """Gets the postal_code of this RegisterRequest.


        :return: The postal_code of this RegisterRequest.
        :rtype: str
        """
        return self._postal_code

    @postal_code.setter
    def postal_code(self, postal_code):
        """Sets the postal_code of this RegisterRequest.


        :param postal_code: The postal_code of this RegisterRequest.
        :type postal_code: str
        """
        if postal_code is None:
            raise ValueError("Invalid value for `postal_code`, must not be `None`")  # noqa: E501
        if postal_code is not None and not re.search(r'^[0-9]{4}-[0-9]{3}$', postal_code):  # noqa: E501
            raise ValueError("Invalid value for `postal_code`, must be a follow pattern or equal to `/^[0-9]{4}-[0-9]{3}$/`")  # noqa: E501

        self._postal_code = postal_code

    @property
    def tarif_type(self):
        """Gets the tarif_type of this RegisterRequest.


        :return: The tarif_type of this RegisterRequest.
        :rtype: TarifType
        """
        return self._tarif_type

    @tarif_type.setter
    def tarif_type(self, tarif_type):
        """Sets the tarif_type of this RegisterRequest.


        :param tarif_type: The tarif_type of this RegisterRequest.
        :type tarif_type: TarifType
        """
        if tarif_type is None:
            raise ValueError("Invalid value for `tarif_type`, must not be `None`")  # noqa: E501

        self._tarif_type = tarif_type

    @property
    def contracted_power(self):
        """Gets the contracted_power of this RegisterRequest.


        :return: The contracted_power of this RegisterRequest.
        :rtype: ContractedPower
        """
        return self._contracted_power

    @contracted_power.setter
    def contracted_power(self, contracted_power):
        """Sets the contracted_power of this RegisterRequest.


        :param contracted_power: The contracted_power of this RegisterRequest.
        :type contracted_power: ContractedPower
        """
        if contracted_power is None:
            raise ValueError("Invalid value for `contracted_power`, must not be `None`")  # noqa: E501

        self._contracted_power = contracted_power

    @property
    def schedule_type(self):
        """Gets the schedule_type of this RegisterRequest.


        :return: The schedule_type of this RegisterRequest.
        :rtype: ScheduleType
        """
        return self._schedule_type

    @schedule_type.setter
    def schedule_type(self, schedule_type):
        """Sets the schedule_type of this RegisterRequest.


        :param schedule_type: The schedule_type of this RegisterRequest.
        :type schedule_type: ScheduleType
        """

        self._schedule_type = schedule_type
