# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from account_manager.models.base_model_ import Model
from account_manager import util


class ScheduleType(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    ECONOMIC = "economic"
    ECOLOGIC = "ecologic"
    def __init__(self):  # noqa: E501
        """ScheduleType - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'ScheduleType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ScheduleType of this ScheduleType.  # noqa: E501
        :rtype: ScheduleType
        """
        return util.deserialize_model(dikt, cls)
