# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from account_manager.models.base_model_ import Model
from account_manager import util


class TarifType(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    SIMPLE = "simple"
    BI_HOURLY = "bi-hourly"
    TRI_HOURLY = "tri-hourly"
    def __init__(self):  # noqa: E501
        """TarifType - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'TarifType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TarifType of this TarifType.  # noqa: E501
        :rtype: TarifType
        """
        return util.deserialize_model(dikt, cls)
