# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from account_manager.models.base_model_ import Model
from account_manager.models.contracted_power import ContractedPower
from account_manager.models.country import Country
from account_manager.models.not_disturb import NotDisturb
from account_manager.models.permission import Permission
from account_manager.models.schedule_type import ScheduleType
from account_manager.models.tarif_type import TarifType
import re
from account_manager import util

from account_manager.models.contracted_power import ContractedPower  # noqa: E501
from account_manager.models.country import Country  # noqa: E501
from account_manager.models.not_disturb import NotDisturb  # noqa: E501
from account_manager.models.permission import Permission  # noqa: E501
from account_manager.models.schedule_type import ScheduleType  # noqa: E501
from account_manager.models.tarif_type import TarifType  # noqa: E501
import re  # noqa: E501

class User(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, user_id=None, first_name=None, last_name=None, email=None, is_active=None, schedule_type=None, meter_id=None, api_key=None, expo_token=None, wp_token=None, country=None, postal_code=None, tarif_type=None, contracted_power=None, not_disturb=None, global_optimizer=None, permissions=None, is_google_account=None, modified_timestamp=None):  # noqa: E501
        """User - a model defined in OpenAPI

        :param user_id: The user_id of this User.  # noqa: E501
        :type user_id: str
        :param first_name: The first_name of this User.  # noqa: E501
        :type first_name: str
        :param last_name: The last_name of this User.  # noqa: E501
        :type last_name: str
        :param email: The email of this User.  # noqa: E501
        :type email: str
        :param is_active: The is_active of this User.  # noqa: E501
        :type is_active: bool
        :param schedule_type: The schedule_type of this User.  # noqa: E501
        :type schedule_type: ScheduleType
        :param meter_id: The meter_id of this User.  # noqa: E501
        :type meter_id: str
        :param api_key: The api_key of this User.  # noqa: E501
        :type api_key: str
        :param expo_token: The expo_token of this User.  # noqa: E501
        :type expo_token: str
        :param wp_token: The wp_token of this User.  # noqa: E501
        :type wp_token: str
        :param country: The country of this User.  # noqa: E501
        :type country: Country
        :param postal_code: The postal_code of this User.  # noqa: E501
        :type postal_code: str
        :param tarif_type: The tarif_type of this User.  # noqa: E501
        :type tarif_type: TarifType
        :param contracted_power: The contracted_power of this User.  # noqa: E501
        :type contracted_power: ContractedPower
        :param not_disturb: The not_disturb of this User.  # noqa: E501
        :type not_disturb: NotDisturb
        :param global_optimizer: The global_optimizer of this User.  # noqa: E501
        :type global_optimizer: bool
        :param permissions: The permissions of this User.  # noqa: E501
        :type permissions: Permission
        :param is_google_account: The is_google_account of this User.  # noqa: E501
        :type is_google_account: bool
        :param modified_timestamp: The modified_timestamp of this User.  # noqa: E501
        :type modified_timestamp: datetime
        """
        self.openapi_types = {
            'user_id': str,
            'first_name': str,
            'last_name': str,
            'email': str,
            'is_active': bool,
            'schedule_type': ScheduleType,
            'meter_id': str,
            'api_key': str,
            'expo_token': str,
            'wp_token': str,
            'country': Country,
            'postal_code': str,
            'tarif_type': TarifType,
            'contracted_power': ContractedPower,
            'not_disturb': NotDisturb,
            'global_optimizer': bool,
            'permissions': Permission,
            'is_google_account': bool,
            'modified_timestamp': datetime
        }

        self.attribute_map = {
            'user_id': 'user_id',
            'first_name': 'first_name',
            'last_name': 'last_name',
            'email': 'email',
            'is_active': 'is_active',
            'schedule_type': 'schedule_type',
            'meter_id': 'meter_id',
            'api_key': 'api_key',
            'expo_token': 'expo_token',
            'wp_token': 'wp_token',
            'country': 'country',
            'postal_code': 'postal_code',
            'tarif_type': 'tarif_type',
            'contracted_power': 'contracted_power',
            'not_disturb': 'not_disturb',
            'global_optimizer': 'global_optimizer',
            'permissions': 'permissions',
            'is_google_account': 'is_google_account',
            'modified_timestamp': 'modified_timestamp'
        }

        self._user_id = user_id
        self._first_name = first_name
        self._last_name = last_name
        self._email = email
        self._is_active = is_active
        self._schedule_type = schedule_type
        self._meter_id = meter_id
        self._api_key = api_key
        self._expo_token = expo_token
        self._wp_token = wp_token
        self._country = country
        self._postal_code = postal_code
        self._tarif_type = tarif_type
        self._contracted_power = contracted_power
        self._not_disturb = not_disturb
        self._global_optimizer = global_optimizer
        self._permissions = permissions
        self._is_google_account = is_google_account
        self._modified_timestamp = modified_timestamp

    @classmethod
    def from_dict(cls, dikt) -> 'User':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The User of this User.  # noqa: E501
        :rtype: User
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user_id(self):
        """Gets the user_id of this User.


        :return: The user_id of this User.
        :rtype: str
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id):
        """Sets the user_id of this User.


        :param user_id: The user_id of this User.
        :type user_id: str
        """
        if user_id is None:
            raise ValueError("Invalid value for `user_id`, must not be `None`")  # noqa: E501
        if user_id is not None and len(user_id) > 10:
            raise ValueError("Invalid value for `user_id`, length must be less than or equal to `10`")  # noqa: E501
        if user_id is not None and len(user_id) < 10:
            raise ValueError("Invalid value for `user_id`, length must be greater than or equal to `10`")  # noqa: E501

        self._user_id = user_id

    @property
    def first_name(self):
        """Gets the first_name of this User.


        :return: The first_name of this User.
        :rtype: str
        """
        return self._first_name

    @first_name.setter
    def first_name(self, first_name):
        """Sets the first_name of this User.


        :param first_name: The first_name of this User.
        :type first_name: str
        """
        if first_name is None:
            raise ValueError("Invalid value for `first_name`, must not be `None`")  # noqa: E501
        if first_name is not None and len(first_name) > 15:
            raise ValueError("Invalid value for `first_name`, length must be less than or equal to `15`")  # noqa: E501
        if first_name is not None and len(first_name) < 1:
            raise ValueError("Invalid value for `first_name`, length must be greater than or equal to `1`")  # noqa: E501

        self._first_name = first_name

    @property
    def last_name(self):
        """Gets the last_name of this User.


        :return: The last_name of this User.
        :rtype: str
        """
        return self._last_name

    @last_name.setter
    def last_name(self, last_name):
        """Sets the last_name of this User.


        :param last_name: The last_name of this User.
        :type last_name: str
        """
        if last_name is not None and len(last_name) > 15:
            raise ValueError("Invalid value for `last_name`, length must be less than or equal to `15`")  # noqa: E501
        if last_name is not None and len(last_name) < 1:
            raise ValueError("Invalid value for `last_name`, length must be greater than or equal to `1`")  # noqa: E501

        self._last_name = last_name

    @property
    def email(self):
        """Gets the email of this User.


        :return: The email of this User.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this User.


        :param email: The email of this User.
        :type email: str
        """
        if email is None:
            raise ValueError("Invalid value for `email`, must not be `None`")  # noqa: E501
        if email is not None and len(email) > 50:
            raise ValueError("Invalid value for `email`, length must be less than or equal to `50`")  # noqa: E501

        self._email = email

    @property
    def is_active(self):
        """Gets the is_active of this User.


        :return: The is_active of this User.
        :rtype: bool
        """
        return self._is_active

    @is_active.setter
    def is_active(self, is_active):
        """Sets the is_active of this User.


        :param is_active: The is_active of this User.
        :type is_active: bool
        """
        if is_active is None:
            raise ValueError("Invalid value for `is_active`, must not be `None`")  # noqa: E501

        self._is_active = is_active

    @property
    def schedule_type(self):
        """Gets the schedule_type of this User.


        :return: The schedule_type of this User.
        :rtype: ScheduleType
        """
        return self._schedule_type

    @schedule_type.setter
    def schedule_type(self, schedule_type):
        """Sets the schedule_type of this User.


        :param schedule_type: The schedule_type of this User.
        :type schedule_type: ScheduleType
        """

        self._schedule_type = schedule_type

    @property
    def meter_id(self):
        """Gets the meter_id of this User.


        :return: The meter_id of this User.
        :rtype: str
        """
        return self._meter_id

    @meter_id.setter
    def meter_id(self, meter_id):
        """Sets the meter_id of this User.


        :param meter_id: The meter_id of this User.
        :type meter_id: str
        """

        self._meter_id = meter_id

    @property
    def api_key(self):
        """Gets the api_key of this User.


        :return: The api_key of this User.
        :rtype: str
        """
        return self._api_key

    @api_key.setter
    def api_key(self, api_key):
        """Sets the api_key of this User.


        :param api_key: The api_key of this User.
        :type api_key: str
        """

        self._api_key = api_key

    @property
    def expo_token(self):
        """Gets the expo_token of this User.


        :return: The expo_token of this User.
        :rtype: str
        """
        return self._expo_token

    @expo_token.setter
    def expo_token(self, expo_token):
        """Sets the expo_token of this User.


        :param expo_token: The expo_token of this User.
        :type expo_token: str
        """

        self._expo_token = expo_token

    @property
    def wp_token(self):
        """Gets the wp_token of this User.


        :return: The wp_token of this User.
        :rtype: str
        """
        return self._wp_token

    @wp_token.setter
    def wp_token(self, wp_token):
        """Sets the wp_token of this User.


        :param wp_token: The wp_token of this User.
        :type wp_token: str
        """

        self._wp_token = wp_token

    @property
    def country(self):
        """Gets the country of this User.


        :return: The country of this User.
        :rtype: Country
        """
        return self._country

    @country.setter
    def country(self, country):
        """Sets the country of this User.


        :param country: The country of this User.
        :type country: Country
        """

        self._country = country

    @property
    def postal_code(self):
        """Gets the postal_code of this User.


        :return: The postal_code of this User.
        :rtype: str
        """
        return self._postal_code

    @postal_code.setter
    def postal_code(self, postal_code):
        """Sets the postal_code of this User.


        :param postal_code: The postal_code of this User.
        :type postal_code: str
        """
        if postal_code is not None and not re.search(r'^[0-9]{4}-[0-9]{3}$', postal_code):  # noqa: E501
            raise ValueError("Invalid value for `postal_code`, must be a follow pattern or equal to `/^[0-9]{4}-[0-9]{3}$/`")  # noqa: E501

        self._postal_code = postal_code

    @property
    def tarif_type(self):
        """Gets the tarif_type of this User.


        :return: The tarif_type of this User.
        :rtype: TarifType
        """
        return self._tarif_type

    @tarif_type.setter
    def tarif_type(self, tarif_type):
        """Sets the tarif_type of this User.


        :param tarif_type: The tarif_type of this User.
        :type tarif_type: TarifType
        """

        self._tarif_type = tarif_type

    @property
    def contracted_power(self):
        """Gets the contracted_power of this User.


        :return: The contracted_power of this User.
        :rtype: ContractedPower
        """
        return self._contracted_power

    @contracted_power.setter
    def contracted_power(self, contracted_power):
        """Sets the contracted_power of this User.


        :param contracted_power: The contracted_power of this User.
        :type contracted_power: ContractedPower
        """

        self._contracted_power = contracted_power

    @property
    def not_disturb(self):
        """Gets the not_disturb of this User.


        :return: The not_disturb of this User.
        :rtype: NotDisturb
        """
        return self._not_disturb

    @not_disturb.setter
    def not_disturb(self, not_disturb):
        """Sets the not_disturb of this User.


        :param not_disturb: The not_disturb of this User.
        :type not_disturb: NotDisturb
        """
        if not_disturb is None:
            raise ValueError("Invalid value for `not_disturb`, must not be `None`")  # noqa: E501

        self._not_disturb = not_disturb

    @property
    def global_optimizer(self):
        """Gets the global_optimizer of this User.


        :return: The global_optimizer of this User.
        :rtype: bool
        """
        return self._global_optimizer

    @global_optimizer.setter
    def global_optimizer(self, global_optimizer):
        """Sets the global_optimizer of this User.


        :param global_optimizer: The global_optimizer of this User.
        :type global_optimizer: bool
        """

        self._global_optimizer = global_optimizer

    @property
    def permissions(self):
        """Gets the permissions of this User.


        :return: The permissions of this User.
        :rtype: Permission
        """
        return self._permissions

    @permissions.setter
    def permissions(self, permissions):
        """Sets the permissions of this User.


        :param permissions: The permissions of this User.
        :type permissions: Permission
        """
        if permissions is None:
            raise ValueError("Invalid value for `permissions`, must not be `None`")  # noqa: E501

        self._permissions = permissions

    @property
    def is_google_account(self):
        """Gets the is_google_account of this User.


        :return: The is_google_account of this User.
        :rtype: bool
        """
        return self._is_google_account

    @is_google_account.setter
    def is_google_account(self, is_google_account):
        """Sets the is_google_account of this User.


        :param is_google_account: The is_google_account of this User.
        :type is_google_account: bool
        """
        if is_google_account is None:
            raise ValueError("Invalid value for `is_google_account`, must not be `None`")  # noqa: E501

        self._is_google_account = is_google_account

    @property
    def modified_timestamp(self):
        """Gets the modified_timestamp of this User.


        :return: The modified_timestamp of this User.
        :rtype: datetime
        """
        return self._modified_timestamp

    @modified_timestamp.setter
    def modified_timestamp(self, modified_timestamp):
        """Sets the modified_timestamp of this User.


        :param modified_timestamp: The modified_timestamp of this User.
        :type modified_timestamp: datetime
        """
        if modified_timestamp is None:
            raise ValueError("Invalid value for `modified_timestamp`, must not be `None`")  # noqa: E501

        self._modified_timestamp = modified_timestamp
