"""Modified language column on DBAppInfoMessages table

Revision ID: b48b348855de
Revises: 792bb38ba432
Create Date: 2023-11-20 21:20:34.647444+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b48b348855de'
down_revision: Union[str, None] = '792bb38ba432'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('app_info_messages', 'language',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.Enum('pt_PT', 'en_GB', name='languageenum', inherit_schema=True),
               postgresql_using='language::languageenum',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('app_info_messages', 'language',
               existing_type=sa.Enum('pt_PT', 'en_GB', name='languageenum', inherit_schema=True),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False)
    # ### end Alembic commands ###
